version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12416jihedCherifa?!
      MYSQL_DATABASE: projectweb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: examsetate-api
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_PASSWORD: 12416jihedCherifa?!

    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - default

    restart: on-failure


  examsstate-front:
    container_name: front-container
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - default

volumes:
  mysql_data:
